sudo: false
language: node_js
branches:
  only:
  - master
node_js:
- 6.10.2
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: TZ7sr3zDROVGk6P6AuVzgjZIA/TBcMsrvqX6buwjrD7/bbrPnng4zIzXt+vqAdfI+W9h6nLnhzHVuZRfXPuPNt9/PQAc9Xu7s9Z09XXWkONWKZkszDzYYtTi5IjSnRjqcQ+Iqqkz1u5myMrKCWbQtdq+1zgLNJwxAXTq2lub5H/sev2euHMWGBGY+0lR+S0bkbFdqr9wa9tnNVBqAi7nQ1z+yOdO6rMu6WdIqpjkCVnEFi/wFi2jkyj51djkfpU1sU70vCf21RxJx1bAtWc2oTytMr65fzZ5Jant29cxNmupE05TVh5JwsswqAaph1Y1N50Rb55xXkW/eZbH7aUuBZfncG79fZZZW1aPA+Rs0YRbbmHsw5OUBc+1NwmTiQjRvvfpprhvVSoAfDJSE64qICb+JW5QYArufj1pE4JrDZVvA3z4NHqVFfS6sf3uWOuaR4HgRRtq2QO5Lhc9KjQhhZdOxmi7Q4YJZ99RdngxdyXPuIRphx4REUq4xf4mbbsAVYfdgUc3O2fPnV+DJAG9RlsKkjpi4KB6Yl79D4U8Q0UKDbVwkH/jLIn3CNaI7SwUvWNwClJz3ON4q18mpro+3U2CF2AZ6znoosOqXL2M0rr0w/+mUtrQaBAC1gfrrSznrzCeoW1yHCjraR/MlMJ7pYRUXvnOeWtBk4OhGdBkosk=
  app:
    master: lunchfinder-client
cache:
  directories:
  - node_modules
